'use strict'

module.exports = {
    grammar : {
        "Terminals": {
            "start": false,
            "encoding": false,
            "mark": false,
            "color": false,
            "fill": false,
            "opacity": false,
            "shape": false,
            "size": false,
            "stroke": false,
            "detail": false,
            "x2": false,
            "y2": false,
            "x": false,
            "y": false,
            "MarkPropFieldDefWithCondition": false,
            "FieldDef": false,
            "PositionFieldDef": false,
            "aggregate": false,
            "bin": false,
            "condition": false,
            "field": false,
            "type": false,
            "sort": false,
            "stack": false,
            "argmax": true,
            "argmin": true,
            "average": true,
            "count": true,
            "distinct": true,
            "max": true,
            "mean": true,
            "median": true,
            "min": true,
            "missing": true,
            "q1": true,
            "q3": true,
            "stderr": true,
            "stdev": true,
            "stdevp": true,
            "sum": true,
            "valid": true,
            "values": true,
            "variance": true,
            "variancep": true
        },
        "Expressions": {
            "start": [["mark", "encoding"]],
            "encoding": [["fill", "opacity", "shape", "size", "color", "stroke","x", "y"]],
            "mark": [["bar"], ["rect"], ["line"], ["point"], ["area"], ["circle"], ["square"]],
            "color": [["bin", "field", "sort", "type"], [], []],
            "fill": [["bin", "field", "sort", "type"], [], []],
            "opacity": [["bin", "field", "sort", "type"], [], []],
            "shape": [["bin", "field", "sort", "type"], [], []],
            "size": [["bin", "field", "sort", "type"], [], []],
            "stroke": [["bin", "field", "sort", "type"], [], []],
            "x": [["aggregate", "bin", "field", "sort", "stack", "type"]],
            "y": [["aggregate", "bin","field", "sort", "stack", "type"], [], []],

            "aggregate": [["mean"],["sum"],["median"],["min"],["max"],["count"], [], [], []],
            "bin": [[true], [], [], []],
            "field": [],
            "type": [["quantitative"], ["ordinal"], ["temporal"], ["nominal"]],
            "sort": [["ascending"], ["descending"], [], [], []],
            "stack": [["zero"], ["center"], ["normalize"], [], [], []]
        },
        "StartingSymbol" : ["start"]
    }
}