'use strict'

module.exports = {
    grammar : {
        "Terminals": {
            "start": false,
            "encoding": false,
            "mark": false,
            "color": false,
            "fill": false,
            "opacity": false,
            "shape": false,
            "size": false,
            "stroke": false,
            "detail": false,
            "x2": false,
            "y2": false,
            "x": false,
            "y": false,
            "MarkPropFieldDefWithCondition": false,
            "FieldDef": false,
            "PositionFieldDef": false,
            "aggregate": false,
            "bin": false,
            "condition": false,
            "field": false,
            "type": false,
            "sort": false,
            "stack": false,
            "argmax": true,
            "argmin": true,
            "average": true,
            "count": true,
            "distinct": true,
            "max": true,
            "mean": true,
            "median": true,
            "min": true,
            "missing": true,
            "q1": true,
            "q3": true,
            "stderr": true,
            "stdev": true,
            "stdevp": true,
            "sum": true,
            "valid": true,
            "values": true,
            "variance": true,
            "variancep": true
        },
        "Expressions": {
            "start": [["mark", "encoding"]],
            "encoding": [["color", "fill", "opacity", "shape", "size", "stroke", "order", "detail", "x2", "y2", "x", "y"]],
            "mark": [["bar"], ["rect"], ["line"], ["point"], ["rule"], ["area"], ["circle"], ["square"]],
            "color": [["MarkPropFieldDefWithCondition"], []],
            "fill": [["MarkPropFieldDefWithCondition"], []],
            "opacity": [["MarkPropFieldDefWithCondition"], []],
            "shape": [["MarkPropFieldDefWithCondition"], []],
            "size": [["MarkPropFieldDefWithCondition"], []],
            "stroke": [["MarkPropFieldDefWithCondition"], []],
            "detail": [["FieldDef"], []],
            "x2": [["FieldDef"], []],
            "y2": [["FieldDef"], []],
            "x": [["PositionFieldDef"], []],
            "y": [["PositionFieldDef"], []],

            "MarkPropFieldDefWithCondition": [["aggregate", "bin", "condition", "field", "sort", "type"]],
            "FieldDef": [["aggregate", "bin", "field", "type"]],
            "PositionFieldDef": [["aggregate", "bin", "field", "sort", "stack", "type"]],

            "aggregate": [["argmax"], ["argmin"], ["average"], ["count"], ["distinct"], ["max"], ["mean"], ["median"], ["min"], ["missing"], ["q1"], ["q3"], ["ci0"], ["ci1"], ["stderr"], ["stdev"], ["stdevp"], ["sum"], ["valid"], ["values"], ["variance"], ["variancep"]],
            "bin": [[true], [false]],
            "condition": [["aggregate"], ["bin"], ["field"], ["type"], ["sort"]],
            "field": [],
            "type": [["quantitative"], ["ordinal"], ["temporal"], ["nominal"]],
            "sort": [["ascending"], ["descending"], [null]],
            "stack": [["zero"], ["center"], ["normalize"], [null]]

        },
        "StartingSymbol" : ["start"]
    }
}